# -*- coding: utf-8 -*-
"""NumpyTask.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_tm9QcesMzbSAHB7ICJNvsP3wuuc6vIP

**Import Numpy Library**
"""

import numpy as np

"""**Practice Tasks**

Practice Tasks (Real-World Style)

1. Sales data (Jan–Dec): [1000, 1200, 1500, 1700, 2000, 2500, 3000, 2800, 2600, 2400, 2200, 2000]

* Extract Q2 sales (Apr–Jun).

* Extract last 6 months’ sales.

2. Employees salaries: [25000, 30000, 40000, 50000, 60000]

* Increase salaries by 15%.

* Find average salary after increment.

3. Exam scores: [30, 40, 45, 50, 55, 60, 65, 70, 75, 80]

* Find mean, median, std.

4. Generate 50 random numbers between 1000 and 5000 (representing shopping bills).

* Find maximum bill, minimum bill, average bill.

* Study hours vs exam scores:

Study: [2, 4, 6, 8, 10]

Scores: [35, 50, 65, 80, 95]

* Find correlation.
"""

# Sales data (Jan–Dec): [1000, 1200, 1500, 1700, 2000, 2500, 3000, 2800, 2600, 2400, 2200, 2000]
sales = np.array([1000, 1200, 1500, 1700, 2000, 2500, 3000, 2800, 2600, 2400, 2200, 2000])
print(sales)

# Extract Q2 sales (Apr–Jun).
print("Q2 Sales: ", sales[4:7])

# Extract last 6 months’ sales.
print("Last 6 month's sales: ", sales)

# Employees salaries: [25000, 30000, 40000, 50000, 60000]
empSalaries = np.array([25000, 30000, 40000, 50000, 60000])
print(empSalaries)

# Increase salaries by 15%.
new_salary = empSalaries * 1.15
print("Increase salaries by 15%: ", new_salary)

# Find average salary after increment.
print("Average salary after increment: ", np.average(new_salary))

# Exam scores: [30, 40, 45, 50, 55, 60, 65, 70, 75, 80]
examScores = np.array([30, 40, 45, 50, 55, 60, 65, 70, 75, 80])
print(examScores)

# Find mean, median, std.
print("Mean", np.mean(examScores))
print("Median", np.median(examScores))
print("Standard Deviation:", np.std(examScores))

# Generate 50 random numbers between 1000 and 5000 (representing shopping bills).
transactions = np.random.randint(1000, 5000, 50)
print(transactions)
# Find maximum bill, minimum bill, average bill.
print("Minimum bill: ", np.min(transactions))
print("Maximum bill: ", np.max(transactions))
print("Average bill: ", np.average(transactions))

# Study hours vs exam scores:
# Study: [2, 4, 6, 8, 10]
study = np.array([2, 4, 6, 8, 10])
print(study)
# Scores: [35, 50, 65, 80, 95]
scores = np.array([35, 50, 65, 80, 95])
print(scores)

# Find correlation.
correlation_matrix = np.corrcoef(study, scores)
print("Correlation Matrix:\n", correlation_matrix)